# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  install_dependencies:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create log directory
        run: mkdir -p ~/Github-action/3-Tier/pipeline-log/tmp-log/tmp-log
      
      - name: Install dependencies
        working-directory: scripts 
        run: |
            chmod +x install-dependency.sh
            ./install-dependency.sh
            
  

